FROM node:18-alpine

WORKDIR /app

# Instalar dependencias del sistema
RUN apk add --no-cache mysql-client

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias de Node
RUN npm install

# Copiar todo el código fuente
COPY . .

# Exponer puerto
EXPOSE 3500

# Comando de inicio
CMD ["node", "server.js"]